# version: "3"
# services:
#   app:
#     build: .
#     ports:
#       - "8080:80"
#     volumes:
#       - ./app/public:/srv/app/public

version: "3"
services:
  phptriage:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/srv/app/public
    env_file:
      - ./docker/env
